name: Validate Dotfiles

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.chezmoiignore'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Test one-liner setup
      run: |
        # Run the one-liner command
        sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply --promptString "Git email address=test@example.com" --promptString "Git user name=test" hirobf10
    
    - name: Verify
      run: |
        echo "=== Verifying dotfiles ==="
        test -f ~/.gitconfig && echo "✅ ~/.gitconfig" || echo "❌ ~/.gitconfig"
        test -f ~/.zshrc && echo "✅ ~/.zshrc" || echo "❌ ~/.zshrc"
        
        echo -e "\n=== Verifying git config ==="
        grep -q "name = test" ~/.gitconfig && echo "✅ Git user name configured" || echo "❌ Git user name not found"
        grep -q "email = test@example.com" ~/.gitconfig && echo "✅ Git email configured" || echo "❌ Git email not found"
        
        echo -e "\n=== Verifying tools ==="
        command -v brew >/dev/null && echo "✅ brew installed" || echo "❌ brew not found"
        command -v chezmoi >/dev/null && echo "✅ chezmoi installed" || echo "❌ chezmoi not found"
        command -v anyenv >/dev/null && echo "✅ anyenv installed" || echo "❌ anyenv not found"
