name: Validate Dotfiles

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.chezmoiignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: macos-14
    
    steps:
    - name: Test one-liner setup
      run: |
        # Run the one-liner command - uses .chezmoidata.yaml defaults
        sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply https://github.com/hirobf10/dotfiles.git
    
    
    - name: Verify setup script execution
      run: |
        # Check that run_once script was executed by chezmoi
        test -f ~/.local/share/chezmoi/run_once_setup.sh
        # Verify installations
        command -v brew
        command -v anyenv
    
    - name: Verify
      run: |
        # Verify chezmoi applied correctly
        test -f ~/.gitconfig
        test -f ~/.zshrc
        test -f ~/.zprofile
        test -f ~/.npmrc
        grep -q "test@" ~/.gitconfig
        
        # Verify setup script installations
        command -v brew
        command -v chezmoi
        command -v direnv
        command -v anyenv
        test -d ~/.oh-my-zsh
