name: Validate Dotfiles

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.chezmoiignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: macos-14
    steps:
    - name: Test one-liner setup
      run: |
        # Run the one-liner command with --no-tty for CI
        sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply --no-tty https://github.com/hirobf10/dotfiles.git
    
    - name: Verify
      run: |
        # Verify chezmoi applied correctly
        test -f ~/.gitconfig
        test -f ~/.zshrc
        test -f ~/.zprofile
        test -f ~/.npmrc
        
        # Verify git config contains expected values
        grep -q "name" ~/.gitconfig
        grep -q "email" ~/.gitconfig
        
        # Verify setup script installations
        command -v brew
        command -v chezmoi
        command -v direnv
        command -v anyenv
        test -d ~/.oh-my-zsh
